<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.33.0.1635" />
    <PackageVersion Include="DungeonChessBattle.Battle.Mod.Interface" Version="0.1.0" />
    <PackageVersion Include="DungeonChessBattle.Game.Mod.Interface" Version="0.1.0" />
  </ItemGroup>
</Project>